const WS_CONSTANT = {
	USERS: "USERS",
	CALL: "CALL",
	OFFER: "OFFER",
	OFFER_PLEASE: "OFFER_PLEASE",
	RESPONSE: "RESPONSE",
	CANDIDATE: "CANDIDATE",
	REGISTRATION: "REGISTRATION",
	NEW_USER : "NEW_USER"
}

export default WS_CONSTANT;